/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 * 
 */
import javax.swing.JOptionPane;
import java.io.*;
public class bank extends javax.swing.JFrame {

    /**
     * Creates new form bank
     */
    public bank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String str, str1;
int choice,z,pin=1234,counter=0,a=3;
int t,s,tab=50000;
JOptionPane.showMessageDialog(null,"Selamat Datang\n ANJUNGAN TUNAI MANDIRI \n BNI SYARIAH-BOJONEGORO \n\nMasukkan 4 Digit PINAnda !","WELCOME",1);
try{
do{
str = JOptionPane.showInputDialog(null, "Masukkan 4 Digit PIN Anda:",
"ATM BNI SYARIAH-BOJONEGORO",0);
pin = Integer.parseInt(str);
counter+=1; //menghitung kesempatan login
if (pin==1234)//cek pin
do{
str =
JOptionPane.showInputDialog(null,"[1] INFORMASI SALDO \n[2] PENYETORAN \n[3] PENARIKAN \n[4] PETUNJUK \n[5] KELUAR \n\nMasukkan Pilihan Menu:","Pilih Transaksi",3);
choice = Integer.parseInt(str);
switch (choice){
case 1:
    JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " + tab); //informasi saldo
z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI SYARIAH-BOJONEGORO",
JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
if (z==0)
break;
else
JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BNI SYARIAH - BOJONEGORO, ambil kartu ATM Anda.");
System.exit(0);
case 2:
str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " ); //menabung
s = Integer.parseInt(str1);
setor hasil = new setor();
hasil.menabung(tab, s);
tab =hasil.getsaldo();
z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI SYARIAH-BOJONEGORO",
JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
if (z==0)
break;
else
JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI, ambil kartu ATM Anda.");
System.exit(0);
case 3:
str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : " ); //pengambilan
t = Integer.parseInt(str1); tarik mengambil = new tarik();
mengambil.ambil(tab,t);
tab =mengambil.getsaldo();
z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI SYARIAH-BOJONEGORO",
JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
if (z==0)
break;
else
JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI, ambil kartu ATM Anda.");
System.exit(0);
case 4:
JOptionPane.showMessageDialog(null,"Cara Penggunaan Aplikasi\n[1] Masukkan PIN dengan benar\n[2] Bertransaksilah dengan benar sesuai pilihan\n[3] Gunakan Uang sesuai kebutuhan dan rajinlah menabung\n ","INFO",1);
break;
case 5:
z=JOptionPane.showConfirmDialog(null,"Anda ingin keluar?","Keluar", JOptionPane.YES_NO_OPTION, 0);
if (z==0){
JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI, ambil kartu ATM Anda");
System.exit(0);
}
else
break;
default: JOptionPane.showMessageDialog(null,"Pilihan menu tidak tersedia\nSilahkan ulangi lagi","ERROR",0);
}
}
while (1==1);
else if (counter<3){ //jika pin salah
a--; //menghitung kesalahan login dan memberikan kesempatan login
JOptionPane.showMessageDialog(null,"Pin Salah !\nPastikan PIN yang anda masukkan benar","ERROR",0);
JOptionPane.showMessageDialog(null,"\nKesempatan login " +
a + " kali lagi" + "\n");
}
else
{
JOptionPane.showMessageDialog(null,"Untuk bantuan nasabah,\nsilahkan menghubungi call center 555123 (Gratis)","Kartu ATM anda diblokir!",0);
System.exit(0);}
}
while (1==1);
}catch (NumberFormatException e){
JOptionPane.showMessageDialog(null,"Kesalahan !\nPastikan kode yang anda masukkan berformat benar! \nPROGRAM KELUAR! \nTerimakasih","ERROR",0);
}
}
}
        /* Create and display the form */
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

